### PR TITLE
GitHub Action to build and upload ktfmt intellij plugin artifact

### PR DESCRIPTION
**Pull request by JavierSegoviaCordoba**
To test this GitHub action it has to be merged to the default branch.

image

I am getting an issue when I change the property to `LATEST-EAP-SNAPSHOT`, in local and with GitHub Actions.

Can you take a look at that problem before merge this PR?

This stack trace:

```
> Configure project :
[gradle-intellij-plugin :ktfmt_idea_plugin] Cannot read builtin registry cache. Run with --debug option to get more log output.
/Users/runner/work/ktfmt/ktfmt/ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/CodeStyleManagerDecorator.java:43: error: CodeStyleManagerDecorator is not abstract and does not override abstract method reformatText(PsiFile,Collection<? extends TextRange>) in CodeStyleManager

class CodeStyleManagerDecorator extends CodeStyleManager
> Task :compileJava
^
/Users/runner/work/ktfmt/ktfmt/ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/CodeStyleManagerDecorator.java:92: error: name clash: reformatText(PsiFile,Collection<TextRange>) in CodeStyleManagerDecorator and reformatText(PsiFile,Collection<? extends TextRange>) in CodeStyleManager have the same erasure, yet neither overrides the other
  public void reformatText(PsiFile file, Collection<TextRange> ranges)
              ^
/Users/runner/work/ktfmt/ktfmt/ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/CodeStyleManagerDecorator.java:91: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/runner/work/ktfmt/ktfmt/ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/CodeStyleManagerDecorator.java:104: error: name clash: reformatTextWithContext(PsiFile,Collection<TextRange>) in CodeStyleManagerDecorator and reformatTextWithContext(PsiFile,Collection<? extends TextRange>) in CodeStyleManager have the same erasure, yet neither overrides the other
  public void reformatTextWithContext(PsiFile file, Collection<TextRange> ranges)
              ^
/Users/runner/work/ktfmt/ktfmt/ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/CodeStyleManagerDecorator.java:103: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/runner/work/ktfmt/ktfmt/ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/KtfmtCodeStyleManager.java:60: error: name clash: reformatText(PsiFile,Collection<TextRange>) in KtfmtCodeStyleManager and reformatText(PsiFile,Collection<? extends TextRange>) in CodeStyleManager have the same erasure, yet neither overrides the other
  public void reformatText(PsiFile file, Collection<TextRange> ranges)
              ^
/Users/runner/work/ktfmt/ktfmt/ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/KtfmtCodeStyleManager.java:70: error: name clash: reformatTextWithContext(PsiFile,Collection<TextRange>) in KtfmtCodeStyleManager and reformatTextWithContext(PsiFile,Collection<? extends TextRange>) in CodeStyleManager have the same erasure, yet neither overrides the other
  public void reformatTextWithContext(PsiFile file, Collection<TextRange> ranges) {
              ^
Note: /Users/runner/work/ktfmt/ktfmt/ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/InitialConfigurationProjectManagerListener.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

### CODE REVIEW

**Comment by JavierSegoviaCordoba** [comment]
I fixed the `override` problem in both files, but it doesn't work for me, so I think I am doing something wrong. I will wait until you have a fix for this.

**Comment by JavierSegoviaCordoba** [comment]
I fixed the `override` in another branch problem but I got a question: the reason that was causing the plugin was incompatible with 2021.1 without releasing a new version maybe is related to this error? So, if future IntelliJ versions don't break like 2021.1, the plugin will work without a new release?

I think ktfmt plugin with the current Gradle/XML configuration will work without upgrading if IntelliJ doesn't change something related to the current implementation.

I am not pushing the fixed branch because it will not work with `2020.3` in Gradle.

PD: I think ktfmt version could fit to be changed here too. If you release a new version of ktfmt without publishing the plugin with it, you could press the button here so someone can download it from here until it is published in the JetBrains plugin repo.

**Comment by cgrushko** [comment]
@JavierSegoviaCordoba - apologies for the delay. Two of ktfmt's maintainers will have reduced availability until May / June, so it'll take us longer than usual to get to all of the good stuff you send our way :) again, apologies...

**Comment by cgrushko** [comment]
@JavierSegoviaCordoba , I just built the plugin locally using gradle, and it worked, though it was against IJ v203.
But that made me realize that building locally works for me, and that I might not benefit from the ability to build it in a GitHub Action. 
Will this be useful for you? is it easier for you than building locally?

**Comment by JavierSegoviaCordoba** [comment]
@cgrushko the idea of this action should be to allow you to try incoming versions without the need to open the IDE, and if the current published version is not compatible, anyone can download the zip without building the project. But it is up to you if you think the problem related to the plugin is incompatible with the next versions can be "solved" by this action without changing the source code, because I think the problem where the plugin is not compatible with 2021 is because it doesn't compile in that version.

**Comment by JavierSegoviaCordoba** [comment]
@cgrushko I think I saw a task to publish the plugin using a Gradle command. Can be interesting to change this action to publish the plugin easily with the latest ktfmt version?

Maybe in an alpha or beta channel.

Or have you planned a way to indicate the ktfmt version in the plugin as a dropdown menu?

**Comment by cgrushko** [comment]
@JavierSegoviaCordoba thanks again for the PR. I took some time to  learn the Action thing and finally created one that publishes the plug-in when a new ktfmt release is published. One thing that's missing is posting build artifacts, which I'll add to the build_and_test.yml file.
